### ISSUE TITLE
iconalias.txt

### ISSUE THREAD

**Issue by christoph-morrison** [fhem/FHEM-Icons-Material-Templarian#4]
Deliver a default iconalias.txt for lazy devStateIcons

**Comment by christoph-morrison** [comment]
Bitte mal testen.

**Comment by FunkOdyssey2001** [comment]
Was soll denn hier getestet werden?
Ob die Datei per Update kommt?

**Comment by christoph-morrison** [comment]
Ja und ob die Datei auch verwendet wird, wenn du ein Update machst.

**Comment by FunkOdyssey2001** [comment]
Ja, es funktioniert.
