### ISSUE TITLE
UPD-Datum ändert sich ohne Änderung der Icons selbst

### ISSUE THREAD

**Issue by FunkOdyssey2001** [fhem/FHEM-Icons-Material-Templarian#5]
Kann man eine Lösung finden, dass FHEM bei einem Update der controls_icons-mdt.txt nicht immer wieder alle Icons herunterladen will? Die Dateien selbst haben sich doch gar nicht geändert, sondern nur das UPD-Datum im Controlfile.

**Comment by sidey79** [comment]
@christoph-morrison 

Die Frage ist, wieso ändert sich das Datum denn überhaupt, wenn sich an der Datei nichts geändert hat, dann sollte sich auch das Datum nicht ändern

**Comment by christoph-morrison** [comment]
Ich denke es liegt daran, dass jedes mal die Icons komplett neu transformiert werden - d.h. wenn die Action läuft, wird jede Datei einmal neu geschrieben und damit bekommt auch jede Datei eine neue ctime/mtime.
Im Prinzip müsste man checken, ob sich was an dem Icon geändert hat und dann müsste entweder neu geschrieben oder halt geskippt werden. Es braucht einen Caching-Mechanismus.

**Comment by sidey79** [comment]
Wenn die Dateien eingecheckt werden und es für git eine Änderung gibt stimme ich dir zu.
Ich denke aber es liegt daran, dass nicht alle commits ausgecheckt werden und die controls-action nicht feststellen kann, wann die Datei wirklich eingecheckt wurde.

Einfach den checkout anpassen, dann sollten nur noch die geladen werden, welche sich auch inhaltlich verändert haben:

```
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
```

**Comment by christoph-morrison** [comment]
Erstmal könnt ihr auf dem master-Branch mit ```update``` bleiben, dann bekommt ihr nicht ständig neue Files beim Update.

**Comment by christoph-morrison** [comment]
> Wenn die Dateien eingecheckt werden und es für git eine Änderung gibt stimme ich dir zu.
> Ich denke aber es liegt daran, dass nicht alle commits ausgecheckt werden und die controls-action nicht feststellen kann, wann die Datei wirklich eingecheckt wurde.
> 
> Einfach den checkout anpassen, dann sollten nur noch die geladen werden, welche sich auch inhaltlich verändert haben:
> 
> ```
>     - uses: actions/checkout@v2
>       with:
>         fetch-depth: 0
> ```

Werde ich ausprobieren. Lerne gerade echt viel über die GH actions :)

**Comment by christoph-morrison** [comment]
Schaut mal in [Job 470247894](https://github.com/fhem/FHEM-Icons-Material-Templarian/actions/runs/470247894) - da wurde nun nur der CHANGED file angepasst, nach dem ich einen Cache implementiert habe.

**Comment by sidey79** [comment]
Ich denke das funktioniert seit d8dc470dd0ccd251a684d77a79faafbe2e6baf58

Dein cache `var/files.cache` wird meiner Meinung nach nirgendwo initalisiert und ist bei jedem Durchlauf leer.

**Comment by sidey79** [comment]
Wie kommen eigentlich die Updates aus dem Repo mit den Icons hier rein, oder ändert sich das eh nie?

**Comment by christoph-morrison** [comment]
> Ich denke das funktioniert seit [d8dc470](https://github.com/fhem/FHEM-Icons-Material-Templarian/commit/d8dc470dd0ccd251a684d77a79faafbe2e6baf58)

Nee, [da](https://github.com/fhem/FHEM-Icons-Material-Templarian/commit/95e13219880539318e1c9b1dc4a1bd2d0176e7bf) wurde ein neuer controlsfile mit nutzlosen `UPD`-Anweisungen geschrieben.

> Dein cache `var/files.cache` wird meiner Meinung nach nirgendwo initalisiert und ist bei jedem Durchlauf leer.

Ich hab lokal den Cache gefüllt und dann mit [comittet](https://github.com/fhem/FHEM-Icons-Material-Templarian/commit/8a6337dfdb391f3a0241690551e7f82b701b0b4c). Das funktioniert soweit auch, es wurde nun kein neuer controlsfile produziert. Was mir beim Nachdenken über deinen Kommentar noch eingefallen ist, ist, dass es aktuell gar keine Möglichkeit gibt den Cache zu invalidieren (falls das aus irgendwelchen Gründen manuell nötig sein sollte). Der Cache ist aktuell so schlau, dass der MD5-Hash ignoriert wird, wenn irgendwas geändert wurde oder der Output doch fehlt. Der Kreuztest mit einem manuell geänderten Source-File steht auch noch aus.

> Wie kommen eigentlich die Updates aus dem Repo mit den Icons hier rein, oder ändert sich das eh nie?

Alle paar Monate kommen neue Icons hinzu, die ich dann aus dem Original-Repo pulle. Es ändert sich also in für die Branche eher tektonischen Zeiträumen. Bis dato habe ich mir aber noch keine Gedanken gemacht das zu automatisieren.

**Comment by sidey79** [comment]
Das var Verzeichnis habe ich irgendwie übersehen :) 

Du könntest eine Cache Action benutzen.
Die wird nach 7 Tagen der nicht Nutzung invalidiert. Das ist aber vermutlich zu knapp.
Dann gibt es noch GitHub Artifacts, die werden nach 90 Tagen gelöscht.

Was mich wundert, dass ich kein commit aller Grafiken gesehen habe. Daher finde ich es komisch, dass diese in der controls Datei einen neuen Zeitstempel bekommen sollen.
Das würde ja nur passieren, wenn sich der Inhalt der generierten Grafiken ändert und das könnte ich nicht feststellen.
Es sei den, der git add Befehl setzt den Zeitstempel auch dann neu, wenn es nichts zum hinzufügen gibt.

Was das automatische aktualisieren angeht hätte ich eine Idee:

Du bindest das Repo aus dem die Grafiken kommen als Submodul ein.
Dann aktivierst Du dependabot um die Submodule zu tracken.
Sobald es dann im anderen git ein commit gibt öffnet dependabot einen Pull Requests :)

**Comment by christoph-morrison** [comment]
> Das var Verzeichnis habe ich irgendwie übersehen :)

Du hast vielleicht einfach in `master` nachgesehen, da gibt es das noch nicht.

> Du könntest eine Cache Action benutzen.
> Die wird nach 7 Tagen der nicht Nutzung invalidiert. Das ist aber vermutlich zu knapp.
> Dann gibt es noch GitHub Artifacts, die werden nach 90 Tagen gelöscht.

Selbst 90 Tage werden zu knapp sein, vermute ich. Ich hab eben noch mal darüber nachgedacht und ich glaube, ich muss gar nicht invalidieren. Ich denke, dass ich die Fälle abgedeckt habe, die zu einem _cache miss_ führen.

> Was mich wundert, dass ich kein commit aller Grafiken gesehen habe. Daher finde ich es komisch, dass diese in der controls Datei einen neuen Zeitstempel bekommen sollen.
> Das würde ja nur passieren, wenn sich der Inhalt der generierten Grafiken ändert und das könnte ich nicht feststellen.
> Es sei den, der git add Befehl setzt den Zeitstempel auch dann neu, wenn es nichts zum hinzufügen gibt.

Sieht so aus. Beim Transform wird wohl die _ctime_ angepasst und damit sieht es dann für deine Action wohl so aus, als wäre die Datei wirklich neu, auch wenn sie inhaltlich identisch ist. Im Prinzip ist das ja auch das Verhalten, dass ich von so einem Update-Generator erwarten würde und das sollte auch nicht dort gelöst werden, sondern wie ich das jetzt implementiert habe, im Konsument der Action. 

> Was das automatische aktualisieren angeht hätte ich eine Idee:
> Du bindest das Repo aus dem die Grafiken kommen als Submodul ein.
> Dann aktivierst Du dependabot um die Submodule zu tracken.
> Sobald es dann im anderen git ein commit gibt öffnet dependabot einen Pull Requests :)

Gute Idee. Werde ich mal ausprobieren. So wie es aussieht, ist das letzte Icon Anfang Dezember 2020 dazu gekommen - wenn das wirklich nur alle paar Monate mal ein neues Bild ist, könnte ich das aber auch manuell leisten denke ich.

**Comment by sidey79** [comment]
Ich hab git add kontrolliert.
Das ändert nichts, wenn die Datei schon vorhanden ist.

Die Action aktualisiert das controls File nur, wenn auch die Datei neu committed wurde. :)

**Comment by christoph-morrison** [comment]
Ja klar, das hab ich ja bisher gemacht. Die Datei wird neu geschrieben und dann mit `git add` das Ausgabeverzeichnis hinzugefügt. Muss das selbst noch mal groken.

Kennst du eigentlich irgendwas mit dem man Github Actions lokal testen kann?

**Comment by sidey79** [comment]
Schau ich mir noch mal in einem Fork näher an. Bisher habe ich es mit add und commit nicht geschafft auf inhaltsgleiche Daten eine Änderung zu erwirken.

Github Actions selbst kann man lokal so direkt nicht testen.
Die JS oder Docker Images die dahinter liegen könnte man testen, aber es ist möglich Debug Logs zu aktivieren:
https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging

Weiterhin kann über https://github.com/marketplace/actions/debugging-with-tmate ein ssh Zugriff auf den runner eingerichtet werden. tmate hat aber so insgesamt seine Eigenheiten, das hab ich schon bei travis-ci kennen gelernt. Lag aber bestimmt an meinem Terminalprogramm...

**Comment by sidey79** [comment]
Lokaler Test war bislang nicht möglich. Ich habe es nicht geschafft die XML Abhängigkeiten zu lösen. :(

Habe es in WSL legacy und in einem Ubuntu 20.04 versucht. Klappt aber nicht, in beiden Fällen klappt ein make nicht. :(
Du kennst nicht zufällig einen Docker Container in dem alles installiert ist ?

**Comment by sidey79** [comment]
@christoph-morrison 

Ich habe es auf einem alpine linux nun testen können.

Ich denke ich weiss auch, wieso sich die Dateien ohne Berücksichtigung des caches ändern:
 
Das perl script speichert die Daten mit CRLF denke ich. Und wenn man die Daten aus dem GIT auf einem Linux auscheckt, dann bekommen sie nur ein LF.

Wenn das Script die Datei neu generiert, dann wieder mit CRLF und dadurch kommt es auch zu einem neuen Commit.


ein .gitattributes würde da vermutlich helfen.
